/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'createdAt' : Time,
  'size' : bigint,
  'mimeType' : string,
  'folderId' : [] | [bigint],
}
export interface Folder {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export interface PaginatedFiles {
  'files' : Array<FileMetadata>,
  'hasMore' : boolean,
}
export type SortDirection = { 'asc' : null } |
  { 'desc' : null };
export type Time = bigint;
export interface UploadResponse { 'id' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFolder' : ActorMethod<[string], [] | [string]>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteFiles' : ActorMethod<[Array<string>], undefined>,
  'deleteFolder' : ActorMethod<[bigint], undefined>,
  /**
   * / New method to get all files regardless of owner
   */
  'getAllFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getAllFolders' : ActorMethod<[], Array<Folder>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[string], [] | [FileMetadata]>,
  'getFilesInFolder' : ActorMethod<[bigint, bigint, bigint], PaginatedFiles>,
  'getPaginatedFiles' : ActorMethod<
    [SortDirection, bigint, bigint],
    PaginatedFiles
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveFileToFolder' : ActorMethod<[string, bigint], undefined>,
  'moveFilesToFolder' : ActorMethod<[Array<string>, bigint], undefined>,
  'removeFromFolder' : ActorMethod<[string], undefined>,
  'renameFolder' : ActorMethod<[bigint, string], undefined>,
  'uploadFile' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    UploadResponse
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];