/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'folderId' : IDL.Opt(IDL.Nat),
});
export const Folder = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const PaginatedFiles = IDL.Record({
  'files' : IDL.Vec(FileMetadata),
  'hasMore' : IDL.Bool,
});
export const SortDirection = IDL.Variant({
  'asc' : IDL.Null,
  'desc' : IDL.Null,
});
export const UploadResponse = IDL.Record({ 'id' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFolder' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'deleteFolder' : IDL.Func([IDL.Nat], [], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getFilesInFolder' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [PaginatedFiles],
      ['query'],
    ),
  'getPaginatedFiles' : IDL.Func(
      [SortDirection, IDL.Nat, IDL.Nat],
      [PaginatedFiles],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moveFileToFolder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'moveFilesToFolder' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [], []),
  'removeFromFolder' : IDL.Func([IDL.Text], [], []),
  'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [UploadResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'folderId' : IDL.Opt(IDL.Nat),
  });
  const Folder = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const PaginatedFiles = IDL.Record({
    'files' : IDL.Vec(FileMetadata),
    'hasMore' : IDL.Bool,
  });
  const SortDirection = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const UploadResponse = IDL.Record({ 'id' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFolder' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'deleteFolder' : IDL.Func([IDL.Nat], [], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
    'getFilesInFolder' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [PaginatedFiles],
        ['query'],
      ),
    'getPaginatedFiles' : IDL.Func(
        [SortDirection, IDL.Nat, IDL.Nat],
        [PaginatedFiles],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moveFileToFolder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'moveFilesToFolder' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [], []),
    'removeFromFolder' : IDL.Func([IDL.Text], [], []),
    'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [UploadResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };