/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'task' : IDL.Text,
  'completed' : IDL.Bool,
  'taskId' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Time,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'folderId' : IDL.Opt(IDL.Nat),
});
export const Folder = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DiagnosticResult = IDL.Record({
  'cycles' : IDL.Nat,
  'build' : IDL.Text,
});
export const PaginatedFiles = IDL.Record({
  'files' : IDL.Vec(FileMetadata),
  'hasMore' : IDL.Bool,
});
export const Mission = IDL.Record({
  'id' : IDL.Nat,
  'tasks' : IDL.Vec(Task),
  'title' : IDL.Text,
  'created' : IDL.Int,
  'owner' : IDL.Principal,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const SortDirection = IDL.Variant({
  'asc' : IDL.Null,
  'desc' : IDL.Null,
});
export const UploadResponse = IDL.Record({ 'id' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFolder' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'createMission' : IDL.Func([IDL.Text, IDL.Vec(Task)], [IDL.Nat], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'deleteFolder' : IDL.Func([IDL.Nat], [], []),
  'deleteMission' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDiagnostics' : IDL.Func([], [DiagnosticResult], ['query']),
  'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
  'getFilesInFolder' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [PaginatedFiles],
      ['query'],
    ),
  'getMission' : IDL.Func([IDL.Nat], [IDL.Opt(Mission)], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getPaginatedFiles' : IDL.Func(
      [SortDirection, IDL.Nat, IDL.Nat],
      [PaginatedFiles],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
  'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'moveFileToFolder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'moveFilesToFolder' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [], []),
  'removeFromFolder' : IDL.Func([IDL.Text], [], []),
  'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMission' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Task)], [], []),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [UploadResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'task' : IDL.Text,
    'completed' : IDL.Bool,
    'taskId' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'folderId' : IDL.Opt(IDL.Nat),
  });
  const Folder = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DiagnosticResult = IDL.Record({
    'cycles' : IDL.Nat,
    'build' : IDL.Text,
  });
  const PaginatedFiles = IDL.Record({
    'files' : IDL.Vec(FileMetadata),
    'hasMore' : IDL.Bool,
  });
  const Mission = IDL.Record({
    'id' : IDL.Nat,
    'tasks' : IDL.Vec(Task),
    'title' : IDL.Text,
    'created' : IDL.Int,
    'owner' : IDL.Principal,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const SortDirection = IDL.Variant({ 'asc' : IDL.Null, 'desc' : IDL.Null });
  const UploadResponse = IDL.Record({ 'id' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFolder' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'createMission' : IDL.Func([IDL.Text, IDL.Vec(Task)], [IDL.Nat], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteFiles' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'deleteFolder' : IDL.Func([IDL.Nat], [], []),
    'deleteMission' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDiagnostics' : IDL.Func([], [DiagnosticResult], ['query']),
    'getFile' : IDL.Func([IDL.Text], [IDL.Opt(FileMetadata)], ['query']),
    'getFilesInFolder' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [PaginatedFiles],
        ['query'],
      ),
    'getMission' : IDL.Func([IDL.Nat], [IDL.Opt(Mission)], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getPaginatedFiles' : IDL.Func(
        [SortDirection, IDL.Nat, IDL.Nat],
        [PaginatedFiles],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMissions' : IDL.Func([], [IDL.Vec(Mission)], ['query']),
    'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'moveFileToFolder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'moveFilesToFolder' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [], []),
    'removeFromFolder' : IDL.Func([IDL.Text], [], []),
    'renameFolder' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMission' : IDL.Func([IDL.Nat, IDL.Text, IDL.Vec(Task)], [], []),
    'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [UploadResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };